# Generated by Django 4.1.4 on 2023-04-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(default='', max_length=100)),
                ('Project_language', models.CharField(default='', max_length=100)),
                ('Project_discription', models.CharField(default='', max_length=1000)),
                ('Project_image', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
